### ISSUE TITLE
[Enhancement] vue.js für die Roadmap

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/create-adapter#107]
@AlCalzone Als Vorschlag für die Roadmap fände ich es genial, wenn neben React auch vue.js ergänzt wird.    Was vue.js aus meiner Sicht so genial macht (wie immer Geschmacksache) ist seine Leichtgewichtigkeit. Es läßt sich perfekt integrieren. Du kannst Dir ja mal den Adapter milight-smart-light anschauen. Hier habe ich für den Admin (index_m.html und auch für die App (Ordner mslfe-ibr; nuxt.js Framework)) vue.js genutzt. Für einen Vergleich von React vs Angular vs Vue schau Dir mal den folgenden Link an: https://www.valuecoders.com/blog/technology-and-apps/vue-js-comparison-angular-react/

**Comment by Apollon77** [comment]
ich denke das Müsste eher im Admin-Repo diskutiert werden. Aktuell geht es eher in Richtung React ...

**Comment by Steiger04** [comment]
@Apollon77 Kennt von Euch denn jemand Vue? Ich könnte mir vorstellen, dass gerade für die Adapterentwickler, die noch nicht so viel Erfahrung haben (dazu gehöre ich auch), gerade Vue den Einstieg sehr erleichtern kann, angefangen vom Einbinden in die index_m.html und der Nutzung als einfache template-Engine (endlich kein jQuery mehr), bis hin zu wirklich komplexen Anwendungen vergleichbar mit Angular. Es muss ja auch kein entweder oder sein, sondern ein sowohl als auch.
