### ISSUE TITLE
Error creating a new adapter using create-adapter

### ISSUE THREAD

**Issue by NECH2004** [ioBroker/create-adapter#119]
Creating a new adapter using the create-adapter script leads to a defective adapter.
causing an error "Unknown packetName \<adapterName\>".
Switching to the file system in can be seen that the directory name is written as io**B**roker.\<adapterName\>.
Changing it to io**b**roker.\<adapterName\> solved the problem.
I think the problem is located in cli.ts (lines 85 ff)

cli.ts:
lines 85 ff

/** CLI-specific functionality for creating the adapter directory */
async function setupProject_CLI(answers: Answers, files: File[]) {
	const rootDirName = path.basename(rootDir);
	// make sure we are working in a directory called ioBroker.\<adapterName\>
	const targetDir = rootDirName.toLowerCase() === 'iobroker.${answers.adapterName.toLowerCase()}'
		? rootDir : path.join(rootDir, 'ioBroker.${answers.adapterName}')
		;
	await writeFiles(targetDir, files);

I think it should be:
	// make sure we are working in a directory called     ##@@**ioBroker**.\<adapterName\>
	const targetDir = rootDirName.toLowerCase() === iobroker.${answers.adapterName.toLowerCase()}
		? rootDir : path.join(rootDir, '**iobroker**.${answers.adapterName}')**
		;

**Comment by AlCalzone** [comment]
I cannot quite follow. Where/when does the error happen? During creation of the adapter files or later? Can you please post a screenshot or a log illustrating the problem?

**Comment by NECH2004** [comment]
The error happens if you try to create an instance of the new adapter. (See video
[01-03-_2019_17-09-21.zip](https://github.com/ioBroker/create-adapter/files/2920219/01-03-_2019_17-09-21.zip)).

**Comment by AlCalzone** [comment]
Ok I see whats going on. You're not supposed to execute that command in the ioBroker folder. It creates the development directory for you, which should have the same name as the GitHub repo (uppercase B).

If you want to test your adapter locally in ioBroker, you have to:
* create a tarball from your dev directory (execute `npm pack`)
* upload it to your ioBroker machine
* and install it locally:
  ```bash
  cd /opt/iobroker
  npm i /path/to/tarball.tgz
  ```
* Afterwards you can just copy&paste the files to your ioBroker machine (and `iobroker upload` if admin files or `io-package.json` was changed)

**Comment by Apollon77** [comment]
Maybe enhance the docs for this case?!

**Comment by AlCalzone** [comment]
> Maybe enhance the docs for this case?!

#12
