### ISSUE TITLE
Add option to "recreate" existing adapter to support migration to new development method

### ISSUE THREAD

**Issue by AWhiteKnight** [ioBroker/create-adapter#122]
No automatic migration of coding, just creation of a proper project for the new development method

**Comment by AlCalzone** [comment]
Do you have some more details what functionality you would expect from this?

**Comment by AWhiteKnight** [comment]
It would be very helpful if the tool could be told to ignore that a certain adapter already exists. Of course the code migration has to be done manually. But creating all the Files needed for the new development method would be very helpful.

**Comment by AlCalzone** [comment]
Okay, I see. That makes a lot of sense.

**Comment by AlCalzone** [comment]
`npx @iobroker/create-adapter --skipAdapterExistenceCheck` - will be released soon.
