### ISSUE TITLE
Implement warning if adapter name is already used, but continue creating 

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/create-adapter#125]
Currently the adapter creator stops when a name is chosen which already exist.
In some cases its very handy to have the possibility to reuse the adapter creator (like currently a lot testing an basic have been change, instead of changing my adapter its would be easier to have a fresh basic from the adapter creator and rebuild my current main.js.

Current situation : Creator does not allow creation of already existing adapters 

Wanted situation : Return warning adapter name already exist in repro xxx, do you want to continue or change the name ?

**Comment by AlCalzone** [comment]
Take a look in the Readme, I added this possibility a few days ago. 😁

**Comment by AlCalzone** [comment]
Except it's an option you have to pass, not an extra question.
