### ISSUE TITLE
"onMessage" is inserted with double quotes in ES6-class template

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/create-adapter#132]

**Comment by AlCalzone** [comment]
Does it come out with double quotes in the finished file? Usually they should be formatted by ESLint which should change the quotes to single.

**Comment by AlCalzone** [comment]
Oh, I see. The line is commented out:
https://github.com/ioBroker/create-adapter/blob/446e801442434812ea9299084ff02ed2811e2dcc/test/baselines/adapter_JS_ES6Class_ESLint_TypeChecking_Spaces_SingleQuotes_LGPLv3/main.js#L27

Therefore it is not formatted. Guess I need to manually set the correct quotes here.

**Comment by Apollon77** [comment]
Dame for the whole onMessage method. Also commented out
