### ISSUE TITLE
Provide a web version of this tool (e.g. on github pages)

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/create-adapter#18]

**Comment by AlCalzone** [comment]
https://stuk.github.io/jszip/

**Comment by AlCalzone** [comment]
We also need a virtual FS as a buffer:
https://raw.githubusercontent.com/AlCalzone/virtual-tsc/master/src/virtual-fs.ts

**Comment by UncleSamSwiss** [comment]
I think, we should improve this:
https://github.com/ioBroker/create-adapter-frontend

Many things are already there and we could just make it a bit more generic, so it doesn't require a lot of work to add a regular question.

**Comment by UncleSamSwiss** [comment]
Web version is now available under https://www.iobroker.dev/create-adapter
Currently only the export to GitHub is supported, but a ZIP file export is already planned:
https://github.com/UncleSamSwiss/iobroker-dev-portal/issues/5
