### ISSUE TITLE
Howto integrate tab_m.html in index_m.html

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/create-adapter#186]
I have generate an "adapter only" for typescript with extra tab. 
In my project I see under the folder admin an index_m.html and an tab_m.html.
When I upload my adapter, I see in the configuration page only the 2 options from index_m.html, no tabs.
How I can activate the file tab_m.html?

**Comment by DutchmanNL** [comment]
This is how I created have in sourceanalytix maybe it helps?

https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/blob/master/admin/index_m.html#L166

**Comment by AlCalzone** [comment]
@truegreyhound Are you talking about a tab layout in the configuration page (index_m) or an additional tab in the admin UI like the script adapter has it (tab_m)?

**Comment by truegreyhound** [comment]
> @truegreyhound Are you talking about a tab layout in the configuration page (index_m) or an additional tab in the admin UI like the script adapter has it (tab_m)?

I'm talking about a tab layout in the configuration page (index_m).  On exceuting the generator, he ask for a extra tab.  in my understanding this mean a tabed configuration page and so I am surprised over the 2 files (index_m and tab_m) and their meaning, okay index_m is clear, but guided from the creater, my expectations was, that tab_m is a part from index:_m and enhanced index_m with tab-functionality.

**Comment by AlCalzone** [comment]
No, I think you misunderstood. The option generates what is necessary for an extra tab in the admin UI (next to Objects, Scripts, and so on). 

What you mean can be achieved this way: https://materializecss.com/tabs.html
