### ISSUE TITLE
Set gulp to version 4 because of the security vulnerabilities in some dependencies

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/create-adapter#20]
package.json -> change devDependencies to gulp 4.0.0

gulpfile.js -> change line 489 from:
      `gulp.task('default', 'updatePackages', 'updateReadme');`
to:
      `gulp.task('default', gulp.series('updatePackages', 'updateReadme'));`

**Comment by AlCalzone** [comment]
I just noticed, gulp wasn't even in the devDependencies.
