### ISSUE TITLE
catch Node 6 installation with an error

### ISSUE THREAD

**Issue by TA2k** [ioBroker/create-adapter#220]
The template is not working with Node 6
because of 	
```
constructor(options) {
		super({
			...options,
			name: "",
		});
```
Maybe you can add a try catch and give an error to update on minimum node 8

**Comment by AlCalzone** [comment]
I see ~~two~~ three options:
1. When creating the adapter files, check if the current machine is running Node <8, and fall back to `Object.assign({}, options, {name: "my-adapter"})`
2. Add the `engines` field to package.json and warn the user on installation
3. Make the creator yell at the developer who is still using Node 6 and don't create any templates if Node is too old

What are your thoughts?
@TA2k @Apollon77 @GermanBluefox

**Comment by TA2k** [comment]
Hi it is more about the user. User with Node 6 getting this error.
To check the engines field at installation sounds good it also helps to bump the installation base to node 8

**Comment by AlCalzone** [comment]
The thing is that setting the engine field does not abort the installation when it does not match - it just warns. There is a workaround, but I'm not sure I like it too much: #78

**Comment by Apollon77** [comment]
Controller 2.0 should check the engine field in io-package
