### ISSUE TITLE
Create Vis-Adapter: travis.yml

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/create-adapter#302]
I created an vis only adapter, but .travis.yml was not created automatically

**Comment by AlCalzone** [comment]
What should be tested in a VIS-only adapter? I guess the package files would make sense.

**Comment by Apollon77** [comment]
We also test that npm install works. But beside this basically package files.

**Comment by AlCalzone** [comment]
Oh you mean because of possible install scripts? Because usually when install fails, it's Travis' fault.

**Comment by Apollon77** [comment]
No, my post was the answer to the question "What should be tested in a VIS-only adapter?"
