### ISSUE TITLE
Vis-Adapter: translation not working

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/create-adapter#303]
I created a vis only adapter, but translation not working.

i figures out that the code 
```
// add translations for edit mode
$.get( "adapter/${widgetName}/words.js", function(script) {
	let translation = script.substring(script.indexOf('{'), script.length);
	translation = translation.substring(0, translation.lastIndexOf(';'));
	$.extend(systemDictionary, JSON.parse(translation));
});
```
overrides the systemDictionary. 

I solved this problem by appending the systemDictionary with the adapter translation:
```
if (vis.editMode) {
    let iobSystemDic = systemDictionary;
    $.get("../vis-materialdesign.admin/words.js", function (script) {
        let translation = script.substring(script.indexOf('{'), script.length);
        translation = translation.substring(0, translation.lastIndexOf(';'));
        $.extend(systemDictionary, JSON.parse(translation));
        $.extend(systemDictionary, iobSystemDic);
    });
}
```

**Comment by AlCalzone** [comment]
I'm not sure about your fix. Shouldn't the (more specific) adapter translation be prioritized? And doesn't the last line overwrite systemDictionary with itself, since `iobSystemDic` references the same object?

**Comment by Scrounger** [comment]
Sure.
No it doesn't overwrite the systemDictionary, it extend it. I use the iobSystemDic, because the loading of adapter specfic tranlastion is async. Result is, as i described above, the systemDictionary will not extend.

**Comment by AlCalzone** [comment]
Could you take a look at https://github.com/ioBroker/create-adapter/pull/306 ? Apparently using `true` as the first parameter of `$.extend` should extend the target, not overwrite it.

**Comment by Scrounger** [comment]
Still not working, sorry.

Seems that the object form sysDic & translation (words.js) are not the same

**Comment by ldittmar81** [comment]
I think Dutch had the same problem an the answer was to put the script on the end of the file:

https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/blob/a782d141e82495935729813e64d45a3ddd5e187a/admin/custom_m.html#L131

**Comment by Scrounger** [comment]
@ldittmar81 
Perfect, that's the solution. I tested it with a vis-adapter.
Test with "normal" adapter will follow

**Comment by Scrounger** [comment]
Ok with a normal adapter its not working.
I solved this problem in my adapter like this
https://github.com/Scrounger/ioBroker.linkeddevices/blob/e2d0339940cac840945c828e4c84c5b2481bf755/admin/custom.js#L7

**Comment by ldittmar81** [comment]
You can also use this:

`
$(window).load(function() {
    $.get......
});
`

**Comment by AlCalzone** [comment]
I'm sure there is a solution that works for both, right? If you guys figure out which one it is, I'll update the template.

**Comment by Scrounger** [comment]
> I think Dutch had the same problem an the answer was to put the script on the end of the file:
> 
> https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/blob/a782d141e82495935729813e64d45a3ddd5e187a/admin/custom_m.html#L131

Unfortunately, this solution does not work.
For the vis-adapter works for me only [this solution](https://github.com/Scrounger/ioBroker.vis-materialdesign/blob/f438562467d9913905b5bd948243f475ecbe687e/widgets/materialdesign/js/materialdesign.js#L11) .

For the adapter works for me only [this solution](https://github.com/Scrounger/ioBroker.linkeddevices/blob/e2d0339940cac840945c828e4c84c5b2481bf755/admin/custom.js#L7)

But i cant figure out where the problem is. At my opinion it depends with the loading of the file because the loading operation is async.

**Comment by AlCalzone** [comment]
Does anyone have an idea how to solve this once and for all?
