### ISSUE TITLE
add *.code-workspace to git and npm ignore

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/create-adapter#309]
forget to do it every time manually :P

**Comment by Apollon77** [comment]
Also .idea ?!

**Comment by AlCalzone** [comment]
> 
> 
> Also .idea ?!

Current master: ;)
![grafik](https://user-images.githubusercontent.com/17641229/66714644-602ff880-edb9-11e9-9fa4-2a3a13ff2e07.png)
