### ISSUE TITLE
not matching gcc version cause error in travis build

### ISSUE THREAD

**Issue by TA2k** [ioBroker/create-adapter#346]
https://travis-ci.org/TA2k/ioBroker.vw-connect/jobs/621692397

caused by different gcc version in travis.yml
https://github.com/ioBroker/create-adapter/blob/master/test/baselines/ci_Travis/.travis.yml
https://github.com/ioBroker/create-adapter/blob/master/templates/_travis.yml.ts

**Comment by TA2k** [comment]
also not included gcc in osx image
https://travis-ci.org/TA2k/ioBroker.vw-connect/jobs/621727975

**Comment by TA2k** [comment]
this one is working
https://github.com/TA2k/ioBroker.vw-connect/blob/master/.travis.yml

**Comment by Apollon77** [comment]
I think GCc 6 would be the correct one up to nodejs 12

**Comment by AlCalzone** [comment]
You could also try github actions which is included in the newest template

**Comment by AlCalzone** [comment]
Fixed in e8b0ae2
