### ISSUE TITLE
support adapter-react

### ISSUE THREAD

**Issue by TA2k** [ioBroker/create-adapter#347]
Is there any plan to support adapter-react as an option?
https://github.com/ioBroker/adapter-react

**Comment by Apollon77** [comment]
I think you need to provide more details and example code and exactly what you think  makes sense here

**Comment by AlCalzone** [comment]
https://github.com/ioBroker/create-adapter#roadmap ==> planned, but I need to find the time.

**Comment by AlCalzone** [comment]
Support for TypeScript+React is coming in the next version. I still need to figure out how to create a similar structure with JS+React.
