### ISSUE TITLE
Add "allow init" option to io-package.json

### ISSUE THREAD

**Issue by klein0r** [ioBroker/create-adapter#376]
When creating a new schedule adapter, you may want to add ```"allowInit": true,``` to the io-package configuration. Would be great if this option will be added in the templates.

**Comment by AlCalzone** [comment]
What does that option do?

**Comment by klein0r** [comment]
@GermanBluefox told me, that schedule adapters (type: schedule) will run immediately with that option on instance restart or when the configuration has been changed / saved. When the option is false, the instance will just run by its cronjob specification.

I've used this on my youtube adapter which collects stats from youtube by schedule to gather information for new channels when the configuration has been changed.

I don't know what's the default of that option (I guess false). I just want you to add it to the configuration file. Maybe you can also ask for the option in the "creation dialog" if schedule has been chosen.

**Comment by AlCalzone** [comment]
Ok sounds good.

**Comment by AlCalzone** [comment]
Will be released shortly as `1.20.0`

**Comment by klein0r** [comment]
Awesome! Thank you

**Comment by Apollon77** [comment]
Yes default is false. ;-)

**Comment by Apollon77** [comment]
Ps: maybe should be true for a schedule Adapter as default? Else the objects are c
Not created before the first schedule run and this confuses users sometimes.

**Comment by klein0r** [comment]
@Apollon77 I was expecting the "true" behavior when I've built schedule adapters. I don't know in which cases you want to avoid the execution on restart / configuration change.
