### ISSUE TITLE
eslint Parsing Error bei der erste Funktion mit async

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/create-adapter#43]
![image](https://user-images.githubusercontent.com/11463809/50423409-29521b80-0855-11e9-904a-4a8c948d673b.png)

**Comment by GermanBluefox** [comment]
Node.js 6 ? Async geht nur mit 8

**Comment by AlCalzone** [comment]
Ich hab ihm gesagt er soll das issue hier aufmachen. Muss im template eine Änderung vornehmen damit eslint async Funktionen versteht.

**Comment by AlCalzone** [comment]
Siehe auch https://github.com/eslint/eslint/issues/10127#issuecomment-377102979 für die Lösung

**Comment by ruhr70** [comment]
**Danke! Funktioniert!**

Ja, node 8 ist im Einsatz und es wurde nur die erste Function mit async als Fehler angezeigt.
