### ISSUE TITLE
adaptername should be checked for the same rules for javascript object/function/variable names

### ISSUE THREAD

**Issue by oweitman** [ioBroker/create-adapter#435]
adaptername should be checked for the same rules for javascript object/function/variable names
because the adapter name is used as a function-name in the widgets code

example i can create a adapter name with a dash in the name.
the widget code fails because  xyz-abc is not a valid javascript functionname

see also 2nd part of the post
https://forum.iobroker.net/topic/31259/m%C3%B6gliches-speicherleck-in-den-templates-f%C3%BCr-adapter-und-vis/3

**Comment by AlCalzone** [comment]
I'd probably rather escape the adapter name in the widget code than forbid more names.

**Comment by oweitman** [comment]
how can you "escape" an name to a valid javascript function name
as an example take adapter name "xyz-abc"
you can only forbid or strip out invalid chars

**Comment by AlCalzone** [comment]
For example by turning `xyz-abc` into `xyz_abc`.

**Comment by AlCalzone** [comment]
closed in #438
