### ISSUE TITLE
package.json property repository.url: the created url doesnt comply with rule E019 of adapter checker

### ISSUE THREAD

**Issue by oweitman** [ioBroker/create-adapter#461]
the created url in the package.json repository.url doesnt comply with the rule E019 of the adapter checker

the adapter create a url in the following scheme
git@github.com:author/ioBroker.adaptername.git

the adapter checker expect the following scheme
git+https://github.com/author/adaptername.git

https://github.com/ioBroker/create-adapter/blob/2ee6615c320d93e119b072d3f90cda5a9861d064/templates/package.json.ts#L74
https://github.com/ioBroker/create-adapter/blob/05ecb2891618ece40991eee911506f8effca1284/src/cli.ts#L160

**Comment by AlCalzone** [comment]
There is an option to switch between git-URLs and https-URLs. HTTPs-URLs should be prefixed with `git+`, but that doesn't currently happen.

About accepting the git@... urls, could you please open an issue in the adapter checker repo? That is perfectly valid if you're authenticating with SSH.

**Comment by AlCalzone** [comment]
I just checked that the https urls are accepted by the adapter checker. So its only the git URLs, which is an issue in the checker.

**Comment by oweitman** [comment]
actualy we didnt have an answer from the adapter-checker.
but maybe the will refering to the following documentation of package.json
https://docs.npmjs.com/files/package.json#git-urls-as-dependencies
an they will only prefixed urls

**Comment by AlCalzone** [comment]
But this is about the repo URL, not dependencies. If you put for example https://github.com/AlCalzone/ioBroker.zwave2 into the [adapter checker](https://adapter-check.iobroker.in/?q=https://github.com/AlCalzone/ioBroker.zwave2), you'll see that there's no error, although the https url is not prefixed with `git+`.
