### ISSUE TITLE
Add TypeScript esLint rule no-floating-promises

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/create-adapter#569]
The following rule should be added for TypeScript in `.eslintrc.js`:
```json
        '@typescript-eslint/no-floating-promises': 'error',
```

This highlights issues where you have async code but forget to call "await" on a method call:
![image](https://user-images.githubusercontent.com/7595126/92091865-a0cda180-edd1-11ea-971d-0b603df29ea4.png)

This error happens often to developers that are new to async/await.

**Comment by AlCalzone** [comment]
Are there any other rules you'd like to be added? I'll do that in one go. I'll probably also include a bunch of rules from https://github.com/AlCalzone/node-zwave-js/blob/master/.eslintrc.js

**Comment by UncleSamSwiss** [comment]
I looked at another project and found a few (debatable) additions (I'm not sure if we have some of them already implicitly):
- https://eslint.org/docs/rules/no-console
- https://eslint.org/docs/rules/no-eval
- https://eslint.org/docs/rules/no-throw-literal
- https://eslint.org/docs/rules/no-use-before-define
- https://eslint.org/docs/rules/sort-imports
- https://eslint.org/docs/rules/prefer-const
- https://eslint.org/docs/rules/no-async-promise-executor
- https://eslint.org/docs/rules/require-await

**Comment by UncleSamSwiss** [comment]
@AlCalzone what else should add in your opinion? I'll make a PR once we agreed on the list.

**Comment by AlCalzone** [comment]
https://eslint.org/docs/rules/sort-imports is okay but we need to make sure it doesn't conflict with Prettier
I'm not 100% sold on https://eslint.org/docs/rules/no-async-promise-executor, because I had situations where this "forbidden" syntax was the most efficient way to handle a mixed Promise/callback API

The others are okay.

I'd add (TypeScript only):
```
		"@typescript-eslint/no-misused-promises": [
			"error",
			{
				checksVoidReturn: false,
			},
		],
```

These are really annoying if not turned off:
```
		"@typescript-eslint/no-unsafe-assignment": "off",
		"@typescript-eslint/no-unsafe-member-access": "off",
		"@typescript-eslint/no-unsafe-return": "off",
		"@typescript-eslint/no-unsafe-call": "off",
```

Some of the base ESLint rules have a `@typescript-eslint/*` version, so we should make sure to prefer them for TypeScript codebases.

**Comment by UncleSamSwiss** [comment]
@AlCalzone I think this should actually be done in https://github.com/ioBroker/adapter-dev/issues/5. Can we close this issue?

**Comment by AlCalzone** [comment]
Yep, but we should note over there what we've discussed here.

**Comment by UncleSamSwiss** [comment]
> Yep, but we should note over there what we've discussed here.

I mentioned it now clearly in the issue, closing this one.
