### ISSUE TITLE
Extract translations from widget and create new task to gulp if necessary

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/create-adapter#58]
https://github.com/ioBroker/create-adapter/blob/master/src/templates/widgets/template.js.ts#L23

Wir sollten die Übersetungen aus dem Widget Ordner auslagern. Entweder in der admin/words.js (alles zusammen) oder unter widgets/words.js -> für die zweite Variante sollten neue Tasks in der gulpfile.js erstellt werden.

**Comment by ldittmar81** [comment]
Um die Übersetzung in admin/words.js zu machen, muss das, anstelle der Übersetzungen rein:
`
$.get( "adapter/ADAPTERNAME/words.js", function(script) {
    let translation = script.substring(script.indexOf('{'), script.length); 
    translation = translation.substring(0, translation.lastIndexOf(';'));   
    $.extend(systemDictionary, JSON.parse(translation));
    });
`

**Comment by AlCalzone** [comment]
PR bitte :)

**Comment by ldittmar81** [comment]
Weil du es bist ;-) ... fertig

**Comment by AlCalzone** [comment]
Closed by #63
