### ISSUE TITLE
type "energy" during install choice missing

### ISSUE THREAD

**Issue by Seqway** [ioBroker/create-adapter#606]
Hello,
first of all thank you for this great setup procedure via create adapter! This is awesome.

During installation it will be asked that you should choose a categorie / type where to put your adapter in.
I didnt find the category "energy".
Can you check this please !

**Comment by AlCalzone** [comment]
It is there:
![grafik](https://user-images.githubusercontent.com/17641229/97675913-2b5c1580-1a90-11eb-8cd8-85a0e3de49ca.png)
