### ISSUE TITLE
Support main branch with name different from master 

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/create-adapter#631]
According to this https://github.com/github/renaming#new-repositories-use-main-as-default-branch-name all new github projects now have the main branch named `main` instead of `master`.
the rest of the article suggests that it is now also possible to use arbitrary branches as main branche. So maybe make it even more variable? Not sure if that is feasible, though.

**Comment by AlCalzone** [comment]
Note to self: detect HEAD branch (requires repo to be configured)
```
$ git remote show origin
* remote origin
  Fetch URL: https://github.com/ioBroker/create-adapter
  Push  URL: https://github.com/ioBroker/create-adapter
  HEAD branch: master
  ...
```

**Comment by AlCalzone** [comment]
Note to self: detect locally-defined default branch name:
```
git config init.defaultBranch
```
(might be empty if not configured)

**Comment by AlCalzone** [comment]
Note to self: detect main branch name from github URL
```
$ git ls-remote --symref https://github.com/zwave-js/node-zwave-js HEAD
ref: refs/heads/master  HEAD
6ddf3bca68537c263849a631d5c117371bfe694a        HEAD
```

**Comment by UncleSamSwiss** [comment]
If somebody creates a new adapter (and thus a new repository), we should now assume the default branch is "main".
I don't think there is any need to check anymore - it's just always "main" and if the user changes it, he'll have to change whatever needs to be changed in the created adapter.
BTW: the only relevant place is the icon in io-package.json
