### ISSUE TITLE
gulp-task for react files

### ISSUE THREAD

**Issue by oweitman** [ioBroker/create-adapter#656]
due to my little knowledge about typescript and the missing knowledge where is the right file, i send my proposal for this task with this issue.
this gulp-task has 2 little additional options:
--del
if this option is given, the task delete all keys in the translated json files which not exists in the en json file
if not given the task writes the count of deletable keys to the console
--notrans
due to the limited quota of google translate, with this option you can ommit the translate call, in case that you only want to clean the files

```
gulp.task("translate-react", async function (done) {
    let yandex;
    let delkeys=false;
    let notrans=true;
    let i;
    //translate service is yandex
    //but free translation service from yandex is stopped
    i = process.argv.indexOf("--yandex");
    if (i > -1) {
        yandex = process.argv[i + 1];
    }
    //in en non existent keys should be deleted in other files
    i = process.argv.indexOf("--del");
    if (i > -1) {
        delkeys = true;
    }
    //translation service should be ommitted in case of quota overuse
    i = process.argv.indexOf("--notrans");
    if (i > -1) {
        notrans = false;
    }
	if (fs.existsSync("./admin/src/i18n/en.json")) {
		let enTranslations = require("./admin/src/i18n/en.json");
		for (let l in languages) {
            let delcount=0;
			console.log("Translate Text: " + l);
			let existing = {};
			if (fs.existsSync("./admin/src/i18n/" + l + ".json")) {
				existing = require("./admin/src/i18n/" + l + ".json");
			}
			for (let t in enTranslations) {
				if (!existing[t]) {
					if (notrans) existing[t] = await translate(enTranslations[t], l, yandex);
				}
			}
            //delete keys which in en not exists
            for (let t in existing) {
                if (!enTranslations[t]) {
                    if (delkeys) {
                        console.log("delete key " + t);
                        delete existing[t];
                    } else {
                        delcount++;
                    }
                }
            }
            if (!delkeys) console.log("deletable keys: "+delcount);
			fs.writeFileSync("./admin/src/i18n/" + l + ".json", JSON.stringify(existing, null, 4));
		}
	}
    fs.writeFileSync("io-package.json", JSON.stringify(iopackage, null, 4));
});
```

PS: i have also wrote a subclass of the i18n-translate class for the admin react part, which i use
in developement process to easy identify my not translated or unused keys and copy paste the json to the en json file. if you are interested, i can post another issue.

**Comment by AlCalzone** [comment]
@UncleSamSwiss thoughts?

**Comment by UncleSamSwiss** [comment]
I think this is overkill. The only thing we need to fix is one line in the gulpfile:
https://github.com/ioBroker/create-adapter/blob/22b7b1889e11566e5d218a74efdafd5f9d841545/templates/gulpfile.js.ts#L320
For React this must be `if (fs.existsSync('./admin/src/i18n/en/translations.json')) {`

**Comment by oweitman** [comment]
i think you have to change a little be more lines, because the directory scheme differs.
src/i18n/en.json    vs    src/i18n/en/translations.json

by the way, i am a fan of distinct tasks for different similar tasks. 
the previous gulp task combines different tasks (translate io-package.json and make translation for the admin interface, but not for the widgets) 
in the end you can combine these distinct tasks to a global translate task in gulp and also call the single task seperatly

**Comment by UncleSamSwiss** [comment]
Important: keep in mind, if we have a React tab and a JS admin UI, we need to use different paths.
See here:
https://github.com/ioBroker/ioBroker.ham/blob/master/gulpfile.js

**Comment by oweitman** [comment]
closed. because no plan to improve
