### ISSUE TITLE
missing package @sentry/browser

### ISSUE THREAD

**Issue by oweitman** [ioBroker/create-adapter#657]
after creating a new adapter the first build:parcel command exits with error

```
olinuc@olinuc:/opt/iobroker/ioBroker.tvprogram$ npm run-script build

> iobroker.tvprogram@0.0.1 build /opt/iobroker/ioBroker.tvprogram
> npm run build:parcel


> iobroker.tvprogram@0.0.1 build:parcel /opt/iobroker/ioBroker.tvprogram
> parcel build admin/src/index.jsx -d admin/build

🚨  /opt/iobroker/ioBroker.tvprogram/node_modules/@iobroker/adapter-react/GenericApp.js:12:45: Cannot resolve dependency '@sentry/browser'
  10 | var _Connection = _interopRequireWildcard(require("./Connection"));
  11 |
> 12 | var Sentry = _interopRequireWildcard(require("@sentry/browser"));
     |                                             ^
  13 |
  14 | var _Error = _interopRequireDefault(require("./Dialogs/Error"));
  15 |
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iobroker.tvprogram@0.0.1 build:parcel: `parcel build admin/src/index.jsx -d admin/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iobroker.tvprogram@0.0.1 build:parcel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2020-12-22T14_33_50_507Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iobroker.tvprogram@0.0.1 build: `npm run build:parcel`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iobroker.tvprogram@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2020-12-22T14_33_50_548Z-debug.log

```

Workaround:
npm install @sentry/browser --save

**Comment by UncleSamSwiss** [comment]
New dependencies are listed here:
https://github.com/ioBroker/adapter-react/#getting-started

**Comment by UncleSamSwiss** [comment]
> Workaround:
> npm install @sentry/browser --save

Should be:
`npm install @sentry/browser --save-dev`

**Comment by oweitman** [comment]
yes, but this package was not automatically installed or applied. 
then there is no information in the documentation  which package the user still has to install after executing create-adapter.

**Comment by UncleSamSwiss** [comment]
Absolutely right. It is a bug (debatable whether in this tool or adapter-react).

I was only referring to the fix. Because we don't want people to accidentally ship this dependency with their adapter.

**Comment by oweitman** [comment]
ok after fix of this issue i will remove the dependency in my package.json
and exceute npm install again

i place the issue here, because in adapter-react i found the missing dependency
in my adapter path

/node_modules/@iobroker/adapter-react/

i didnt find the package.json of adapter-react

**Comment by AlCalzone** [comment]
As discussed in telegram, dependencies that adapter-react needs should be put into the dependencies there instead of devDependencies.
We can't be duplicating the dependencies and just hope it keeps working.

**Comment by AlCalzone** [comment]
https://github.com/ioBroker/adapter-react/issues/10 is the actual bug here.
