### ISSUE TITLE
Enable sourcemaps for TypeScript

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/create-adapter#687]
If one wants to debug, sourcemaps should be enabled for Typescript Adapter code.

Also, `.gitignore` should be adjusted to either ignore `*.map` or not ignore `maps/`. I'm not sure what makes more sense (check in source maps or not?)

**Comment by AlCalzone** [comment]
Good point - I thought they were on.

**Comment by AlCalzone** [comment]
I think we should also check them in. If I remember correctly, ioBroker loads the `sourcemap-support` module, so the error messages should actually show the `.ts` sources then.
