### ISSUE TITLE
Add .github to .npmignore

### ISSUE THREAD

**Issue by klein0r** [ioBroker/create-adapter#688]

**Comment by AlCalzone** [comment]
Sounds good, although I strongly advocate to whitelist files that should go into the released package with the `files` entry in `package.json` instead.

**Comment by UncleSamSwiss** [comment]
All dot-directories are already ignored. See:
- Template: https://github.com/ioBroker/create-adapter/blob/bd9ec5f892b24d01c3a51cb98375e2867b387b4f/templates/_npmignore.ts#L12
- Example: https://github.com/ioBroker/create-adapter/blob/bd9ec5f892b24d01c3a51cb98375e2867b387b4f/test/baselines/adapter_JS_ES6Class_ESLint_TypeChecking_Spaces_SingleQuotes_Apache-2.0/.npmignore#L1

**Comment by AlCalzone** [comment]
Can you verify that `npm pack` does indeed not include `.github/`?

**Comment by UncleSamSwiss** [comment]
![image](https://user-images.githubusercontent.com/7595126/109185961-c6d86b00-7790-11eb-9f53-f3183af2da6d.png)

```bash
$ npm pack
npm notice 
npm notice package: iobroker.luxtronik2@0.1.2
npm notice === Tarball Contents === 
npm notice 11.5kB LICENSE                    
npm notice 749B   admin/style.css            
npm notice 4.6kB  admin/index_m.html         
npm notice 119B   build/lux-messages.js      
npm notice 14.3kB build/lux-meta.js          
npm notice 23.8kB build/main.js              
npm notice 3.6kB  build/lib/tools.js         
npm notice 2.8kB  admin/words.js             
npm notice 7.3kB  io-package.json            
npm notice 2.5kB  package.json
npm notice 476B   build/debug.log
npm notice 2.6kB  debug.log
npm notice 13.6kB README.md
npm notice 4.1kB  admin/luxtronik2.png
npm notice 2.3kB  admin/admin.d.ts
npm notice === Tarball Details === 
npm notice name:          iobroker.luxtronik2
npm notice version:       0.1.2
npm notice filename:      iobroker.luxtronik2-0.1.2.tgz
npm notice package size:  27.9 kB
npm notice unpacked size: 94.5 kB
npm notice shasum:        827c3cff190a259af290dae761cc017f6f819bd4
npm notice integrity:     sha512-xb/uKn1H//gCp[...]WhfkAiWLjQXfw==
npm notice total files:   15
npm notice
iobroker.luxtronik2-0.1.2.tgz
```

**Comment by AlCalzone** [comment]
Alright, then there's nothing to do here

**Comment by klein0r** [comment]
> All dot-directories are already ignored. See:

Sorry - looks like I've used an older version 😢

**Comment by UncleSamSwiss** [comment]
> Sounds good, although I strongly advocate to whitelist files that should go into the released package with the `files` entry in `package.json` instead.

Created #694
