### ISSUE TITLE
Title error

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/create-adapter#72]
![title](https://user-images.githubusercontent.com/9552828/51487773-2ee34880-1da4-11e9-8969-43eaa94362e1.png)

Siehe hier: https://github.com/ioBroker/ioBroker.repochecker/blob/master/index.js#L158

Title should not have ioBroker in the name. It is clear, for what this adapter was created.
Title should not have word "adapter" in the name. It is clear, that this is adapter.

**Comment by AlCalzone** [comment]
?

**Comment by ldittmar81** [comment]
Ich habe als Titel ein Text geschrieben und dann kam der Fehler. Hab dann das  'not' überlesen und 'must contain adapter' verstanden. Das wäre natürlich falsch... Mir ist eigentlich gar nicht aufgefallen, dass ich 'adapter' im Titel hatte... Kurz gesagt: zu wenig Kaffee.
