### ISSUE TITLE
Support for JSON Admin UI

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/create-adapter#724]
Similar to #723, we should also support the new format for regular adapter configuration.

**Comment by UncleSamSwiss** [comment]
Schema:
https://github.com/ioBroker/ioBroker.admin/blob/master/src-rx/src/components/JsonConfigComponent/SCHEMA.md

Example from ioBroker.sayit:
- Config: https://github.com/Jey-Cee/ioBroker.sayit/blob/master/admin/jsonConfig.json
- io-package.json: https://github.com/Jey-Cee/ioBroker.sayit/blob/b1b9a2e00b769844bc1952b625faa738d5294a78/io-package.json#L202

**Comment by UncleSamSwiss** [comment]
Keep in mind:
- Minimum admin dependency: version 5
- we have to create an almost empty index_m.html because people can use "classic mode" in Admin 5

**Comment by Apollon77** [comment]
We shopuld also add an i18n directory with needed content and provide the translated texts there when we add jsonconfig stuff and ideally prevent people from using jsonconfig with "included i18n"

**Comment by AlCalzone** [comment]
fixed by #911
