### ISSUE TITLE
Update to React 17

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/create-adapter#749]
We have pinned the React versions to 16.x as a precaution. In my experience this isn't necessary, as React 17 is backwards compatible.

**Comment by Apollon77** [comment]
I remember @UncleSamSwiss and me had build issues in ham adaoter React UI when going to v17

**Comment by AlCalzone** [comment]
Really? Do you remember what exactly?

**Comment by Apollon77** [comment]
nope ... sorry ...

**Comment by UncleSamSwiss** [comment]
no, don't remember either, but the issue was with https://github.com/ioBroker/ioBroker.ham admin tab.
