### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Xenon-s** [ioBroker/create-adapter#751]
Error occurred in Google Chrome

![image](https://user-images.githubusercontent.com/65488191/117830032-8fe40280-b273-11eb-9630-1d8f76a6973c.png)

https://flaviocopes.com/parcel-regeneratorruntime-not-defined/

**Comment by UncleSamSwiss** [comment]
Basically something like this is missing:
```json
"browserslist": [
  "since 2017-06"
]
```

**Comment by AlCalzone** [comment]
Is that an issue in adapter-react (which itself is transpiled) or here? I have never seen that in my React builds and I definitely don't have browserslist configured.

**Comment by UncleSamSwiss** [comment]
It happens with adapter-react (I believe because it is using async), but in the end, the browserlist must be (and should be) added in the end product (i.e. the adapter). We need to ensure parcel is emitting for the right browsers.

**Comment by AlCalzone** [comment]
I think it's safe to assume that all relevant browsers support `async`

**Comment by UncleSamSwiss** [comment]
> I think it's safe to assume that all relevant browsers support `async`

Absolutely. Unfortunately if you try to use `Dialogs/SelectID`, parcel will fail with the above error message.
The solution is thus to add the browserslist to package.json as mentioned in my first comment.

**Comment by AlCalzone** [comment]
or drop parcel in favor of esbuild :)

**Comment by UncleSamSwiss** [comment]
Yes, as it is [apparently](https://github.com/evanw/esbuild/issues/121) not using browserlist.

**Comment by swissglider** [comment]
For me this helped:

- npm install --save regenerator-runtime
- add "import 'regenerator-runtime/runtime'" where you call the dialog.

https://dev.to/hulyakarakaya/how-to-fix-regeneratorruntime-is-not-defined-doj

**Comment by AlCalzone** [comment]
Should be fixed by #839, which switched to esbuild internally
