### ISSUE TITLE
Switch to ES2019 for TypeScript

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/create-adapter#757]
As the comment says:
"Consider targetting es2019 or higher if you only support Node.js 12+"

https://github.com/ioBroker/create-adapter/blob/0f73f4f3df838523f148e6a5677d8608c4a6aa52/templates/tsconfig.json.ts#L42

**Comment by UncleSamSwiss** [comment]
This would of course also mean that we don't support Node.js 10 anymore (which should be configured that way in package.json/io-package.json)

**Comment by AlCalzone** [comment]
I think this is fair. We should edit that comment to ES2020 and Node 14 when we do that.
And I think this is a good time to use https://github.com/tsconfig/bases as a reference (see the adapter-dev repo)

**Comment by AlCalzone** [comment]
Just verified with @Apollon77. We'll drop support for Node 10 in JS-Controller 3.4 - but that should not concern new adapters.

**Comment by UncleSamSwiss** [comment]
But I think also new adapters should run on the oldest Node version that is officially supported by ioBroker (i.e. js-controller). So, I would prefer to have Node 12 support also in new adapters.
