### ISSUE TITLE
New created adapter fails starting with: cannot find start file

### ISSUE THREAD

**Issue by jmades** [ioBroker/create-adapter#778]
I just created a new adpater with the command line tool (npx @iobroker/create-adapter).
[iobroker.pumpcontrol2.zip](https://github.com/ioBroker/create-adapter/files/6770069/iobroker.pumpcontrol2.zip)

Installing the adaper from github (or by copying it to /opt/iobroker/node_modules shows the adapter in the adapter list, bit when installing it fails with error: host.raspRS485 startInstance pumpcontrol2.0: cannot find start file!

iobroker running on rasperry Pi 3, Node version v12.22.2.

**Comment by Garfonso** [comment]
Which js-controller version? Try latest (3.3.14). 
Maybe even use [dev-server](https://github.com/ioBroker/dev-server) for development (which will use latest js-controller).

**Comment by AlCalzone** [comment]
Yeah, `io-package.json` doesn't contain a `"main"` entry, so it looks like your JS-Controller is a bit old.

**Comment by jmades** [comment]
I have 3.2.16 installed...I will try an update

**Comment by UncleSamSwiss** [comment]
All OK, but a newly created adapter shouldn't fail with 3.2!

**Comment by AlCalzone** [comment]
Yeah, we should fix this. This was done because of the JSON Schema in JS-Controller (but that isn't backwards compatible).

**Comment by AlCalzone** [comment]
@jmades add this to `io-package.json` inside `"common": {...}`

```jsonc
"main": "build/main.js"
```

**Comment by UncleSamSwiss** [comment]
> Yeah, we should fix this. This was done because of the JSON Schema in JS-Controller (but that isn't backwards compatible).

Should we update the schema to have this element at least optionally? Otherwise many people will adjust their package.json after running a schema test and thus break the adapter for <=3.2.x

**Comment by jmades** [comment]
> ```js
> "main": "build/main.js"
> ```

Ok, this solves the problem :-)

**Comment by Garfonso** [comment]
> 
> 
> > Yeah, we should fix this. This was done because of the JSON Schema in JS-Controller (but that isn't backwards compatible).
> 
> Should we update the schema to have this element at least optionally? Otherwise many people will adjust their package.json after running a schema test and thus break the adapter for <=3.2.x

Yes, we should probably do that. I failed for this at least two times already, too...

**Comment by UncleSamSwiss** [comment]
> Yes, we should probably do that.

Where, who and how?

**Comment by AlCalzone** [comment]
> Where

JS-Controller Repo

> who

foxriver

> how

that way: https://github.com/ioBroker/ioBroker.js-controller/commit/aeb188c9d0ba7a161e0ffa11d5274c360c91ba2c

Now we need to edit the io-package.json template.
