### ISSUE TITLE
Include work around to require a minimum nodejs version

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/create-adapter#78]
Implement the idea of https://medium.com/@adambisek/how-to-check-minimum-required-node-js-version-4a78a8855a0f to generate an error on installing with an unsupported nodejs version to restore npm "strictEngine" feature

**Comment by AlCalzone** [comment]
Is this still relevant? I think we have a check in the js-controller now.

**Comment by Apollon77** [comment]
the check in controller is only to prevent the start ... installing would be allowed still ... ideally we still do something like this

**Comment by AlCalzone** [comment]
Wouldn't it be better to have that field on the repo and check before starting the installation then? This way, npm cannot mess things up before noticing that the package won't work.

**Comment by Apollon77** [comment]
Controller 2.2.8 will bring the feature for adapter install.

**Comment by Apollon77** [comment]
BTW: js-controller will most likely do the npm install and if successfull and it can read the package.json it will throw an eror then and no instance will be created! So the problem is still there for upgrades. I still would like to completely hinder people from doing npm install als when bypassing iobroker commands to install

**Comment by AlCalzone** [comment]
Then we should do the same for js-controller. A friend of mine upgraded from an ancient version to 2.x, that failed (probably because of a node incompatibility), and he was left without a js-controller.

**Comment by AlCalzone** [comment]
We should just set `engine-strict` to true in .npmrc (--> Fixer/Installer)
![grafik](https://user-images.githubusercontent.com/17641229/72892812-ceb91680-3d17-11ea-8f31-b1257d65795c.png)

**Comment by AlCalzone** [comment]
This has been implemented in the latest fixer/installer
