### ISSUE TITLE
Update Travis-CI URL to .com (instead of .org)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/create-adapter#791]
"Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on."

<img width="941" alt="Screenshot 2021-08-03 at 10 25 49" src="https://user-images.githubusercontent.com/1959049/127983476-32501062-859e-4cfb-aa83-261c1ea186fa.png">

**Comment by AlCalzone** [comment]
Honestly, we should just remove Travis from the template. Github Actions is better and faster.

Any takers?
@Apollon77 @UncleSamSwiss ?

**Comment by UncleSamSwiss** [comment]
@AlCalzone Absolutely! There is IMHO no need to support Travis with the creator. This doesn't affect existing adapters and if somebody really wants to use Travis, he's free to do so on his own.

This also simplifies the creator a bit (one option less to choose from).

**Comment by klein0r** [comment]
Good to know! Just moved everything to travis.com .... and now my free credits are already used. 😢

**Comment by Apollon77** [comment]
kill travis ... with fire ... burn it ... move to github actions :-) (sorry)

**Comment by joergzdarsky** [comment]
> Good to know! Just moved everything to travis.com .... and now my free credits are already used. 😢

Same here. Need to check how to get rid of travis again now in my syncthing adapter. Found that too late unfortunately.

**Comment by klein0r** [comment]
@joergzdarsky Just use the github actions of this repo: https://github.com/ioBroker/create-adapter/tree/master/templates/_github

I've dropped travisci everywhere

**Comment by AlCalzone** [comment]
> Need to check how to get rid of travis again now in my syncthing adapter

https://github.com/ioBroker/create-adapter/blob/master/docs/updates/20210818_no_travis.md
