### ISSUE TITLE
gulp translation works not out of the box

### ISSUE THREAD

**Issue by jlssmt** [ioBroker/create-adapter#794]
create-adapter adds i18n structure like this:
`./admin/src/i18n/en.json`

delivered gulpfile.js instead works with 
`./admin/i18n/en/translations.json`

there are two issues:
1. for typescript react (?) there is a src folder
2. create-adapter does not create a folder for every language.

you can use my code to meet the requirements, or otherwise change the create-adapter structure to folders.

```
if (fs.existsSync('./admin/src/i18n/en.json')) {
            let enTranslations = require('./admin/src/i18n/en.json');
            for (let l in languages) {
                console.log('Translate Text: ' + l);
                let existing = {};
                if (fs.existsSync('./admin/src/i18n/' + l + '.json')) {
                    existing = require('./admin/src/i18n/' + l + '.json');
                }
                for (let t in enTranslations) {
                    if (!existing[t]) {
                        existing[t] = await translate(enTranslations[t], l, yandex);
                    }
                }
                fs.writeFileSync('./admin/src/i18n/' + l + '.json', JSON.stringify(existing, null, 4));
            }
        }
```

**Comment by AlCalzone** [comment]
@UncleSamSwiss I think you touched that last?

**Comment by UncleSamSwiss** [comment]
Yes, this is broken. It will be replaced by the new adapter-dev as soon as it is ready. I think we should release adapter-dev soon (translation is ready, everything else is currently missing) and then immediately integrate it into a new version of create-adapter.

**Comment by UncleSamSwiss** [comment]
Update to adapter-dev is tracked in #742.
