### ISSUE TITLE
Add the possibility to create Issue templates

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/create-adapter#85]
see e. g. https://github.com/foxriver76/ioBroker.sonnen/tree/master/.github/ISSUE_TEMPLATE
GitHub will automatically uses files structured like this as templates. When opening an issue you can choose between bug and feature and also PR templates are possible if this is necessary for us like in https://github.com/foxriver76/ioBroker.sonnen/issues/new/choose 

The template should ask the creator of the bug at least for OS, js-c version, adapter version and Node version.

Additional info: https://help.github.com/articles/about-issue-and-pull-request-templates/

**Comment by AlCalzone** [comment]
I just looked at your examples. What is the table at the start for?

**Comment by foxriver76** [comment]
Automatic assignment and automatic labeling of an issue, as well as for the description seen here: https://github.com/foxriver76/ioBroker.sonnen/issues/new/choose

**Comment by foxriver76** [comment]
Thanks for the integration, should be added to npmignore template too.
